SELECT T.INNER_NODE, 
IF(T.B IS NULL,'Root',NAME) FROM
(
    SELECT DISTINCT B1.N AS 'INNER_NODE', 'Inner' AS NAME, B1.P AS B
    FROM BST AS B1 INNER JOIN BST AS B2 ON B1.N=B2.P
UNION
    SELECT N AS 'INNER_NODE', 'Leaf' AS NAME, P AS B
    FROM BST
    WHERE N NOT IN (SELECT DISTINCT B1.N AS 'INNER_NODE'
    FROM BST AS B1 INNER JOIN BST AS B2 ON B1.N=B2.P)
UNION
    SELECT P AS 'INNER_NODE', 'Root' AS NAME, N AS B
    FROM BST
    WHERE P NOT IN (SELECT DISTINCT B1.N AS 'INNER_NODE'
    FROM BST AS B1 INNER JOIN BST AS B2 ON B1.N=B2.P))
AS T ORDER BY T.INNER_NODE;