SET @X1=(SELECT MIN(LAT_N)
FROM STATION);
SET @Y1=(SELECT MIN(LONG_W)
FROM STATION);
SET @X2=(SELECT MAX(LAT_N)
FROM STATION);
SET @Y2=(SELECT MAX(LONG_W)
FROM STATION);
SELECT ROUND((ABS(@X1-@X2)+ABS(@Y1-@Y2)),4);