SET @X1=(SELECT MIN(LAT_N)
FROM STATION);
SET @Y1=(SELECT MIN(LONG_W)
FROM STATION);
SET @X2=(SELECT MAX(LAT_N)
FROM STATION);
SET @Y2=(SELECT MAX(LONG_W)
FROM STATION);
SELECT ROUND(SQRT(POWER(@X1-@X2, 2)+POWER(@Y1-@Y2, 2)),4);